
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Admin
 */
public class przelaczniki extends javax.swing.JFrame {

    /**
     * Creates new form przelaczniki
     */
    public przelaczniki() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        przelacznikRozmiaru = new javax.swing.ButtonGroup();
        maly = new javax.swing.JRadioButton();
        sredni = new javax.swing.JRadioButton();
        duzy = new javax.swing.JRadioButton();
        etykieta = new javax.swing.JLabel();

        przelacznikRozmiaru.add(maly);
        przelacznikRozmiaru.add(sredni);
        przelacznikRozmiaru.add(duzy);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        maly.setText("przelacznik1");
        maly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                malyActionPerformed(evt);
            }
        });

        sredni.setText("przelacznik2");
        sredni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sredniActionPerformed(evt);
            }
        });

        duzy.setText("duzy");
        duzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duzyActionPerformed(evt);
            }
        });

        etykieta.setText("Program");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(maly, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sredni, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(duzy, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(etykieta, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {duzy, maly, sredni});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maly)
                    .addComponent(sredni)
                    .addComponent(duzy))
                .addGap(49, 49, 49)
                .addComponent(etykieta)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {duzy, maly, sredni});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void malyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_malyActionPerformed
etykieta.setFont(new Font("Dialog", Font.BOLD, 10));    }//GEN-LAST:event_malyActionPerformed

    private void sredniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sredniActionPerformed
        etykieta.setFont(new Font("Dialog", Font.BOLD, 20));
    }//GEN-LAST:event_sredniActionPerformed

    private void duzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duzyActionPerformed
etykieta.setFont(new Font("Dialog", Font.BOLD, 30));    }//GEN-LAST:event_duzyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(przelaczniki.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new przelaczniki().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton duzy;
    private javax.swing.JLabel etykieta;
    private javax.swing.JRadioButton maly;
    private javax.swing.ButtonGroup przelacznikRozmiaru;
    private javax.swing.JRadioButton sredni;
    // End of variables declaration//GEN-END:variables
}
